version: '3'
services:

  # redis:
  #   image: redis
  #   restart: always

  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    expose:
      - "5000"
    

      
